name: Automation

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
    - uses: cleartax/jira-lint@master
      name: jira-lint
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        jira-token: ${{ secrets.JIRA_TOKEN }}
        jira-base-url: https://umusic.atlassian.net
        pr-threshold: 1000
    - uses: kentaro-m/task-completed-checker-action@v0.1.2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
